package: api
generate:
  models: true
  strict-server: true
  embedded-spec: true
  chi-server: true
output: api/api.gen.go
output-options:
  skip-prune: true
  exclude-schemas: []
  exclude-tags: []
  include-tags: []
import-mapping:
  ./api/openapi.yaml: github.com/despiegk/goweb2/api
additional-imports:
  - package: github.com/go-chi/chi/v5
    alias: chi
