package: generated
generate:
  models: true
  strict-server: true
  embedded-spec: true
  chi-server: true
output: api/generated/api.gen.go
output-options:
  skip-prune: true
  exclude-schemas: []
  exclude-tags: []
  include-tags: []
additional-imports:
  - package: github.com/go-chi/chi/v5
    alias: chi
